spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        generate_statistics: false
        default_schema: schema
  datasource:
    url: ${DB_URL}
    password: ${DB_PWD}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog.xml
    default-schema: schema
    liquibase-schema: schema
springdoc:
  swagger-ui:
    display-request-duration: true